apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-main-d-aor-velero-ngx1
  namespace: rmp
  labels:
    environmentShortName: lab
    regionShortName: main
    partitionShortName: d
    serviceShortName: velero
    clusterSuffix: ngx1
    clusterTitle: lab-main-d-aor-velero-ngx1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lab-main-d-aor-velero-ngx1
  resources:
    requests:
      storage: 5Gi
