apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backuprepositories.velero.io
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/version: v1.14.0
spec:
  group: velero.io
  names:
    kind: BackupRepository
    listKind: BackupRepositoryList
    plural: backuprepositories
    singular: backuprepository
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                provider:
                  description: The name of the backup repository provider (e.g., aws, gcp, azure).
                  type: string
                config:
                  description: Configuration for the backup repository provider.
                  type: object
                  additionalProperties:
                    type: string
                credential:
                  description: The name of a Kubernetes secret containing credentials for the backup repository provider.
                  type: string
                objectStorage:
                  description: Configuration for object storage if required by the provider.
                  type: object
                  additionalProperties:
                    type: string
                region:
                  description: The region where the backup repository is located.
                  type: string
            status:
              type: object
              properties:
                phase:
                  description: The current phase of the BackupRepository.
                  type: string
                message:
                  description: Any additional message about the status of the backup repository.
                  type: string
  conversion:
    strategy: None
  preserveUnknownFields: false

