apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: deletebackuprequests.velero.io
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/version: v1.14.0
spec:
  group: velero.io
  names:
    kind: DeleteBackupRequest
    listKind: DeleteBackupRequestList
    plural: deletebackuprequests
    singular: deletebackuprequest
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                backupName:
                  description: The name of the backup to delete.
                  type: string
            status:
              type: object
              properties:
                phase:
                  description: The current phase of the delete backup request.
                  type: string
                errors:
                  description: Errors encountered while processing the delete backup request.
                  type: array
                  items:
                    type: string
                expiration:
                  description: When the delete backup request will expire.
                  type: string
  conversion:
    strategy: None
  preserveUnknownFields: false

