apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podvolumebackups.velero.io
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/version: v1.14.0
spec:
  group: velero.io
  names:
    kind: PodVolumeBackup
    listKind: PodVolumeBackupList
    plural: podvolumebackups
    singular: podvolumebackup
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                backup:
                  description: The name of the Velero backup object this object corresponds to.
                  type: string
                node:
                  description: The name of the Kubernetes node that the pod is running on.
                  type: string
                pod:
                  description: The name of the pod containing the volume to be backed up.
                  type: string
                namespace:
                  description: The namespace that contains the pod.
                  type: string
                volume:
                  description: The name of the volume within the pod to be backed up.
                  type: string
                repoIdentifier:
                  description: The unique identifier for the volume backup repository.
                  type: string
                tags:
                  description: The tags to apply to the backup (AWS/GCP specific).
                  type: object
                  additionalProperties:
                    type: string
                snapshotID:
                  description: The ID of the snapshot of the volume being backed up.
                  type: string
                progress:
                  description: Tracks the progress of the backup process.
                  type: object
                  properties:
                    totalBytes:
                      type: integer
                    bytesDone:
                      type: integer
            status:
              type: object
              properties:
                phase:
                  description: The current phase of the PodVolumeBackup.
                  type: string
                message:
                  description: Any additional message about the backup's status.
                  type: string
                progress:
                  description: Progress status of the backup process.
                  type: object
                  properties:
                    totalBytes:
                      type: integer
                    bytesDone:
                      type: integer
  conversion:
    strategy: None
  preserveUnknownFields: false

