apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podvolumerestores.velero.io
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/version: v1.14.0
spec:
  group: velero.io
  names:
    kind: PodVolumeRestore
    listKind: PodVolumeRestoreList
    plural: podvolumerestores
    singular: podvolumerestore
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                restore:
                  description: The name of the Velero restore object this object corresponds to.
                  type: string
                node:
                  description: The name of the Kubernetes node that the pod is running on.
                  type: string
                pod:
                  description: The name of the pod containing the volume to be restored.
                  type: string
                namespace:
                  description: The namespace that contains the pod.
                  type: string
                volume:
                  description: The name of the volume within the pod to be restored.
                  type: string
                repoIdentifier:
                  description: The unique identifier for the volume backup repository.
                  type: string
                snapshotID:
                  description: The ID of the snapshot of the volume being restored.
                  type: string
                progress:
                  description: Tracks the progress of the restore process.
                  type: object
                  properties:
                    totalBytes:
                      type: integer
                    bytesDone:
                      type: integer
            status:
              type: object
              properties:
                phase:
                  description: The current phase of the PodVolumeRestore.
                  type: string
                message:
                  description: Any additional message about the restore's status.
                  type: string
                progress:
                  description: Progress status of the restore process.
                  type: object
                  properties:
                    totalBytes:
                      type: integer
                    bytesDone:
                      type: integer
  conversion:
    strategy: None
  preserveUnknownFields: false

