apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: restores.velero.io
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/version: v1.14.0
spec:
  group: velero.io
  names:
    kind: Restore
    listKind: RestoreList
    plural: restores
    singular: restore
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                backupName:
                  description: The name of the Velero backup object this restore corresponds to.
                  type: string
                includedNamespaces:
                  description: A list of namespaces to include in the restore.
                  type: array
                  items:
                    type: string
                excludedNamespaces:
                  description: A list of namespaces to exclude from the restore.
                  type: array
                  items:
                    type: string
                includedResources:
                  description: A list of resources to include in the restore.
                  type: array
                  items:
                    type: string
                excludedResources:
                  description: A list of resources to exclude from the restore.
                  type: array
                  items:
                    type: string
                namespaceMappings:
                  description: A mapping of source namespace names to target namespace names.
                  type: object
                  additionalProperties:
                    type: string
                labelSelector:
                  description: A label selector to filter objects to restore.
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                restorePVs:
                  description: Whether to restore PersistentVolumes as part of the restore process.
                  type: boolean
                volumeSnapshotsEnabled:
                  description: Whether to enable volume snapshot restores.
                  type: boolean
            status:
              type: object
              properties:
                phase:
                  description: The current phase of the Restore.
                  type: string
                message:
                  description: Any additional message about the restore's status.
                  type: string
                progress:
                  description: Progress of the restore process.
                  type: object
                  properties:
                    totalItems:
                      type: integer
                    itemsRestored:
                      type: integer
  conversion:
    strategy: None
  preserveUnknownFields: false

