apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: schedules.velero.io
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/version: v1.14.0
spec:
  group: velero.io
  names:
    kind: Schedule
    listKind: ScheduleList
    plural: schedules
    singular: schedule
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                template:
                  description: Defines the Velero backup spec that will be created on each scheduled run.
                  type: object
                  properties:
                    ttl:
                      description: The time-to-live (TTL) for the backup.
                      type: string
                    includedNamespaces:
                      description: A list of namespaces to include in the backup.
                      type: array
                      items:
                        type: string
                    excludedNamespaces:
                      description: A list of namespaces to exclude from the backup.
                      type: array
                      items:
                        type: string
                    includedResources:
                      description: A list of resources to include in the backup.
                      type: array
                      items:
                        type: string
                    excludedResources:
                      description: A list of resources to exclude from the backup.
                      type: array
                      items:
                        type: string
                    labelSelector:
                      description: A label selector to filter objects for the backup.
                      type: object
                      properties:
                        matchLabels:
                          type: object
                          additionalProperties:
                            type: string
                    snapshotVolumes:
                      description: Whether to snapshot PersistentVolumeClaims during the backup.
                      type: boolean
                    volumeSnapshotsEnabled:
                      description: Enable volume snapshot backup.
                      type: boolean
                schedule:
                  description: A Cron expression that defines the backup schedule.
                  type: string
            status:
              type: object
              properties:
                phase:
                  description: The current phase of the Schedule.
                  type: string
                lastBackup:
                  description: The time when the last backup was created by the schedule.
                  type: string
                message:
                  description: A message about the last backup's status.
                  type: string
  conversion:
    strategy: None
  preserveUnknownFields: false

