apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serverstatusrequests.velero.io
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/version: v1.14.0
spec:
  group: velero.io
  names:
    kind: ServerStatusRequest
    listKind: ServerStatusRequestList
    plural: serverstatusrequests
    singular: serverstatusrequest
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                serverName:
                  description: The name of the Velero server to check the status of.
                  type: string
                status:
                  description: The status to set for the server.
                  type: string
                  enum:
                    - Online
                    - Offline
                    - Maintenance
            status:
              type: object
              properties:
                phase:
                  description: The current phase of the ServerStatusRequest.
                  type: string
                message:
                  description: Any additional message about the status request.
                  type: string
  conversion:
    strategy: None
  preserveUnknownFields: false

