apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumesnapshotlocations.velero.io
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/version: v1.14.0
spec:
  group: velero.io
  names:
    kind: VolumeSnapshotLocation
    listKind: VolumeSnapshotLocationList
    plural: volumesnapshotlocations
    singular: volumesnapshotlocation
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                provider:
                  description: The name of the volume snapshot provider (e.g., aws, gcp, azure).
                  type: string
                config:
                  description: Configuration for the volume snapshot provider.
                  type: object
                  additionalProperties:
                    type: string
                credential:
                  description: The name of a Kubernetes secret containing credentials for the volume snapshot provider.
                  type: string
                objectStorage:
                  description: Configuration for object storage if required by the provider.
                  type: object
                  additionalProperties:
                    type: string
                region:
                  description: The region where the volume snapshot location is located.
                  type: string
            status:
              type: object
              properties:
                phase:
                  description: The current phase of the VolumeSnapshotLocation.
                  type: string
                message:
                  description: Any additional message about the status of the volume snapshot location.
                  type: string
  conversion:
    strategy: None
  preserveUnknownFields: false

