apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
  labels:
    tags.datadoghq.com/env: lab
    tags.datadoghq.com/service: velero-ews1
    tags.datadoghq.com/version: 2.0.22
  annotations:
    # cluster designator
    cts/k8cluster: eks1
spec:
  provider: aws
  objectStorage:
    bucket: velero-backups-lab
    prefix: backups
  config:
    region: us-west-2
    s3ForcePathStyle: "false"
