---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lab-main-d-aor-velero-ews1
  namespace: velero
  labels:
    environmentShortName: lab
    regionShortName: main
    partitionShortName: d
    serviceShortName: velero
    clusterSuffix: ews1
    clusterTitle: lab-main-d-aor-velero-ews1
data:
  backup-storage-location-0: |
    name: default
    provider: aws
    bucket: velero-backups-lab
    config:
      region: us-west-2
