apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lab-main-d-aor-restic-ews1
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "persistentvolumeclaims", "persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["velero.io"]
    resources: ["backups", "restores", "schedules", "backupstoragelocations", "serverstatusrequests" , "volumesnapshotlocations", "resticrepositories", "downloadrequests", "deletebackuprequests", "podvolumebackups", "podvolumerestores" , "backuprepositories"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lab-main-d-aor-restic-ews1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lab-main-d-aor-restic-ews1
subjects:
  - kind: ServiceAccount
    name: lab-main-d-aor-velero-ews1
    namespace: velero
